### ISSUE TITLE
Add default ID to when creating new entity

### ISSUE THREAD

**Issue by caseyyee** [aframevr/aframe-inspector#108]
So we don't end up with a sea of a-entity objects in the scene graph.

ie:

Cube
Cube-1
Cube-2

Torus
Torus-1
Torus-2

Ambient-1

etc.

**Comment by dmarcos** [comment]
How do you decide on a default id that is not just a random string? A cube primitive might also have a light, or a model won't have a primitive geometry. What about entities that only have 3rd party components and we cannot infer semantics for? Another problem would be user defined id's mixed with the default ones making the scene graph confusing and potentially error prone when using `querySelector' or due to collisions

**Comment by caseyyee** [comment]
All good points.  the issue still stands though. We end up with a soup of entities that becomes unserviceable in both the visual editor and markup.  There needs to be a solution for this.  Open to other ideas and will also think through possible solution to this.

**Comment by dmarcos** [comment]
That's one of the reasons to have the icons annotating the scene graph. They will help you visually discriminate entities quickly and give details about each components when you hover on them. For instance: you have multiple entities with a geometry and you want to find the icosaedron. You can hover on the icons and via tooltip see the property values without having to click on them.

**Comment by caseyyee** [comment]
I don't want to debate the icons here, it's not a solution to the problem.   It all looks the same.   A bunch of Icons won't help anything here.

**Comment by cvan** [comment]
Isn't this fixed?

**Comment by cvan** [comment]
Oh, nevermind it's not. For cloning only.

**Comment by ngokevin** [comment]
IDs should be dev set and are only useful when there's code attached to them anyways
