### ISSUE TITLE
Consider hiding "Attributes" sidebar when no scene-graph entity is selected

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#165]
1. Load a scene with the editor mode.
2. Notice an empty "Attributes" sidebar appears:

![image](https://cloud.githubusercontent.com/assets/203725/16681883/43b75fc2-44ac-11e6-88ec-39687f7c7f0f.png)

**Comment by fernandojsg** [comment]
I've already implemented this feature but didn't apply a PR yet because we need to decide how to deal with the toolbar.
Right now the toolbar has absolute position next to the sidebar, so if we just hide the sidebar, it will looks like:
<img width="1435" alt="screenshot 2016-08-04 17 12 16" src="https://cloud.githubusercontent.com/assets/782511/17407277/eb4553aa-5a66-11e6-8406-b270961e72f4.png">

There're some options to del with this:
1) Move it to the center
<img width="1436" alt="screenshot 2016-08-04 17 12 55" src="https://cloud.githubusercontent.com/assets/782511/17407316/1b64e988-5a67-11e6-8820-7c111a0918d7.png">

2) Align it to the left next to scenegraph
<img width="1423" alt="screenshot 2016-08-04 17 13 06" src="https://cloud.githubusercontent.com/assets/782511/17407331/2dc98f2a-5a67-11e6-95e3-1e12b6f48f28.png">

3) Align to the right so once the sidebar will hide, it will jump to the right.
<img width="1436" alt="screenshot 2016-08-04 17 14 24" src="https://cloud.githubusercontent.com/assets/782511/17407346/3790ba42-5a67-11e6-84ff-a06a1ba4a983.png">

**Comment by dmarcos** [comment]
I would align to the right so it's consistent when the component panel is shown
