### ISSUE TITLE
Enable drag and drop of scene graph entities

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#19]
I'd like to move one entity to be nested within another entity. Or I'd like to just rearrange or group my entities.

**Comment by fernandojsg** [comment]
I believe to do that (moving nodes from the DOM) the components should be deleted and recreated again after moving right?

**Comment by dmarcos** [comment]
That's tricky. We would have to add a detach/attach API to components. Components can rely on certain info about where they are in the scene graph.

**Comment by cvan** [comment]
We can use flexbox to change the `order` in which the entities are displayed. See https://github.com/cvan/flexbox-sort. And then when exporting, you can actually do the rearranging before you export the HTML.

**Comment by cvan** [comment]
Without the ability to at least rearrange the top-level order of the entities, I can see it being very confusing figuring out how to group related entities without having to delete a bunch of entities and re-enter them.

The scene-graph sidebar should reflect the order in which the entities appear(ed) in the markup, yeah?

**Comment by fernandojsg** [comment]
Yes the scenegraph reflect the entities as they appear in the markup, so if we want to reorder them or change the hierarchy we should deattach&attach them to the DOM again as @dmarcos says.
So it's more like a API problem than related to the editor. Until we'll get a solution on how to do that we could implement the search/filter functionality on the scenegraph.
But we should keep consistency on the scenegraph with the DOM not to confuse the user.

**Comment by caseyyee** [comment]
Looking into this issue.   

Looks like there are some components to easily do this:

http://tamagokun.github.io/example-react-dnd-nested/

I would _really_ like to see this since it will really help organize the scene graph -- especially if your jumping back and forth between markup and the visual editor.

**Comment by fernandojsg** [comment]
I use not to reinvent the wheel every time I need a new widget, but sometimes If we need something very specific it's probably the best way to go, like for example the numeric widget that we've right now.
Looking at that repo it seems like a very huge source code like just include in our project: https://github.com/gaearon/react-dnd/tree/master/src
We should keep in mind that the scenegraph will evolve in many ways, it will act like a treeview where you could collapse/expand its nodes so we should implement features like this one in that source code and maintain the changes with the original repo :\ 
So probably it could be a better idea to try to do something by ourselves, or if it's just like a proof of concept without the idea of merge into the main repo sure just give it a try.

**Comment by ngokevin** [comment]
I can see this discussion getting down on the purpose of the Editor. Is the Editor complementary to the markup, or should it be its own product that hides the markup? I believe we somewhat are on the same page about it being more of an Inspector/Tweaker rather than the primary development tool.

If the Editor is to be the primary development tool, then DnD makes sense. Because then you rearrange your entities, and then you get neat HTML. Your interface _is_ the Scene Graph, and it is necessary to keep it readable.

However, if the markup is the focus, which I contend it is, then I'd think that you would clean your HTML source if you wanted a clean scene graph. The scene graph represents the HTML, not the other way around, so we might want to prescribe that developers address the source rather than try to implement some sort of visual coding tool.

This has the added benefit of removing complexity away from the Editor, both in terms of maintenance and not having the deal with the potential unpredictability of detaching and attaching entities.

I saw @caseyyee post a screenshot of messy HTML of the Editor example scene. I believe we could address that by cleaning up the HTML itself, and it looks even messier than it is because you aren't the author of the source. Whereas if you _were_ the author of the source, you would be more intimate with the scene structure.

**Comment by ngokevin** [comment]
wontfixing
