### ISSUE TITLE
Multiple components

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#190]
Options for showing the name of multiple components on the components list:
- 1 The component name itself
  <img width="924" alt="screenshot 2016-06-29 01 52 54" src="https://cloud.githubusercontent.com/assets/782511/16740645/5403cd60-47a0-11e6-8703-aab2ecd6a657.png">
- 2 COMPONENT_NAME (_InstanceID_)
  <img width="331" alt="screenshot 2016-06-29 01 57 11" src="https://cloud.githubusercontent.com/assets/782511/16740647/58ed43a6-47a0-11e6-9f1f-944f15e3c58d.png">
- 3 INSTANCE_ID (_ComponentName_)
  <img width="327" alt="screenshot 2016-06-29 01 56 26" src="https://cloud.githubusercontent.com/assets/782511/16740649/5908ec1e-47a0-11e6-9ebc-07c92164c8ba.png">
- 4 COMPONENT_NAME INSTANCEID
  <img width="331" alt="screenshot 2016-06-29 03 16 02" src="https://cloud.githubusercontent.com/assets/782511/16740659/6238b33c-47a0-11e6-8192-224ed6bca74f.png">

**Comment by fernandojsg** [comment]
I like **4** the most

**Comment by dmarcos** [comment]
I like **1**. It's simpler, more compact and not redundant. It just shows the component name and its ID as they appear in the element attribute. It gives you all the information you need. Notice that the separator is double underscore `__` instead of underscore `_`.  It also leaves more space for buttons associated to the component.
