### ISSUE TITLE
Cheat sheet panel to show the available shortcuts

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#276]

**Comment by ngokevin** [comment]
I like MagicaVoxel's shortcut panel at the bottom. It displays the shortcut for whatever action you are currently hovering over (i.e., given the context), rather than a giant list of shortcuts.

<img width="1004" alt="screen shot 2016-08-18 at 3 01 08 am" src="https://cloud.githubusercontent.com/assets/674727/17769966/264ed550-64f0-11e6-9c1d-7cff129ca549.png">

**Comment by fernandojsg** [comment]
We could add something like `h` for a fullscreen modal with all the shortcuts like a cheatsheet, and also adding the statusbar with the current action while hover the mouse, I like that
