### ISSUE TITLE
Adding/removing mixins is a bit confusing

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#28]
I know it's probably obvious to most, but I didn't actually understand that pressing the plus sign was taking the actively selected mixin in the `<select>` and adding it below.

I originally thought the `mixins` `<select>` menu was listing the active mixins on that entity:

![image](https://cloud.githubusercontent.com/assets/203725/16507937/d896ec04-3ee2-11e6-86dd-a76e5544efcf.png)

**Comment by cvan** [comment]
Same goes for components:

![image](https://cloud.githubusercontent.com/assets/203725/16507964/0845f148-3ee3-11e6-8902-c547f3223f45.png)

It's confusing, at least to me, that "Components" is its own group but then the added components don't become children/sub-sections of "Components"

**Comment by fernandojsg** [comment]
Yes you're right, this is something we were discussing with Dennis and waiting for a final proposal. Related to https://github.com/aframevr/aframe-editor/issues/17

**Comment by ngokevin** [comment]
I'd consider moving `Components` into the `Common` group, and then renaming `Common` to reflect that its root-level Entity type of stuff.

**Comment by feiss** [comment]
Regarding mixins, I think the problem is that the name displayed is the name of a mixin:
![image](https://cloud.githubusercontent.com/assets/359872/20138721/31f58984-a682-11e6-85f1-946eb09fae61.png)

We could replicate the same visual style and behaviour of `Add Component`. It should display: `Add mixin...`, and then the `+` button is not longer necessary. Just when the user selects a mixin from the list, it is automatically added. I think it is a much simpler, clean, easy and standard behaviour.

![image](https://cloud.githubusercontent.com/assets/359872/20138833/0b954de6-a683-11e6-848b-18660426f7c1.png)

**Comment by fernandojsg** [comment]
@feiss nice idea, I like it! :+1:

**Comment by ngokevin** [comment]
added multiselect
