### ISSUE TITLE
Should "Copy HTML" for an entity include unaltered/empty components?

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-inspector#310]
For example, see `material="" geometry=""`:

``` html
<a-entity id="shortOrangeBox" mixin="short orange box" position="-5 2 0" material="" geometry=""></a-entity>
```

**Comment by fernandojsg** [comment]
Right now "copy html" is removing default values and default components that has default values too (`position="0 0 0"` for example). The problem with this one is that it has a `material` and a `geometry` defined on the mixins, so it will need some logic to know that they're already defined in the mixins, so we could delete the empty values.
The problem is what to do if we have something like: 

```
<a-entity id="shortOrangeBox" mixin="short orange box" position="-5 2 0" geometry="primitive:box; width:2; height:3"></a-entity>
```

And the geometry is also defined in the mixins. Should we just delete the empty components defined in the mixins and leave the ones that has some value?
/cc @ngokevin
