### ISSUE TITLE
Text over icons and menu bar

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#315]
This is an issue we've been discussing in different issues and regarding the menu we already had one one but removed it after some brainstorming about it. 
But with the recent icons and now that we're in a situation where we're going to start adding more functionality I believe it's good to have one discussion about it.

We removed icons on the components title bar to use text instead
![image](https://cloud.githubusercontent.com/assets/203725/17805011/44726138-65b2-11e6-999e-e86668c44808.png)
And we should do that change too in the entity options for consistency with the previous one (https://github.com/aframevr/aframe-inspector/issues/311)

And the same goes for the scenegraph (https://github.com/aframevr/aframe-inspector/issues/265):
![image](https://cloud.githubusercontent.com/assets/203725/17610694/690573ea-5ff5-11e6-93ef-be0e2edc275a.png)

We've also discussed it on https://github.com/aframevr/aframe-inspector/issues/166

I agree that looking at examples like sketch or keynote the UI is very clean and intuitive
<img width="1552" alt="screen shot 2016-07-08 at 2 29 52 am" src="https://cloud.githubusercontent.com/assets/203725/16683298/e4859e80-44b3-11e6-8d1e-286b17609f42.png">

![10-html-export-opt](https://cloud.githubusercontent.com/assets/782511/17808146/a64e480c-660e-11e6-9109-6c6b0afea278.png)

But they're just exposing some of the most common used options, they still have a menubar for the rest of less commonly used features. And in fact I don't find an icon for one action while learning the UI I could always go to the menu and spot the option I want as it's a easy way to group and order all the actions of the application. For example for this issue: https://github.com/aframevr/aframe-inspector/issues/311 it's clear that it's an UI/UX issue but you could keep working if you see `Edit -> Copy entity to HTML` or whatever.

My main concern is to end up with an UI without icons and full of text, and trying to expose almost every action on the UI ruining the UX and the overall aesthetics. I also don't feel like doing a witch hunt for the icons could be that good, people got used of using icons daily in their phones, and apps everywhere, in fact, having the app just in English could be harder entry point for non-english speakers if we just use text for every option instead of using icons that they could already know.

One example of UI that get rid of the menu and try to put as much options on the UI could be the new Microsoft Office suite where the options tabs is changing constantly based on the context, that makes hard to remember the position of the options and sometimes you can go crazy looking for an option because you've selected a cell instead of the whole table, or so on.

Looking at the Vizor approach, they've a huge list of options and you have to scroll them or use the search box. I would prefer having them in a menu that it's easier for grouping the options. Regarding the searchbox I really like it, in fact we had a prototype to include a searchbox similar to spotlight or sublimetext where you could select entities quickly or do some actions:
![image](https://cloud.githubusercontent.com/assets/782511/17808708/db4fb63c-6611-11e6-9ce5-33f4fc3169b6.png)

Let's brainstorm! :)

**Comment by feiss** [comment]
I think the menu bar is interesting when the rest of the application is confusing in some part. If the tool was simple and very easy to pick up there would be no need of it. Right now I think there are issues regarding the UI that should be improved, but there aren't really so many features and options that justify the need of adding a menu bar.

BUT, I find the menu bar would be beneficial in two aspects:
- If the app grows a lot in terms of functionality, it's a very safe place where new options/actions can be added, instead of dangerously cluttering the UI.
- It's also a very safe, very known place where users can go if they are a bit lost. Yes, it's very traditional, maybe ugly, but it does work.

Also, the screen space it takes is insignificant comparing to the mentioned benefits, and frames the whole application and gives the user a starting/home point.

So: I think a menu bar is interesting in terms of scalability and usability, specially for future versions.

## 

**Regarding icon labels:** I think they are necessary if icons are confusing and not clear enough, which is the case now, but I think they could be fixed. The think is: if the application grows, there will be much less space for icon labels. Examples like Sketch or Keynote are not very appropriate, because they have a toolbar, a dedicated, scalable space for icons, which we don't have.

(btw, instead of labels, nice, big tooltips could be useful although not very mobile friendly).

**Comment by cvan** [comment]
> **Regarding icon labels:** I think they are necessary if icons are confusing and not clear enough, which is the case now, but I think they could be fixed.

agreed, yes.

> The think is: if the application grows, there will be much less space for icon labels.

how do we expect the application to grow?

> Examples like Sketch or Keynote are not very appropriate, because they have a toolbar, a dedicated, scalable space for icons, which we don't have.

why might not we be able to afford a dedicated space for icons? (see below for possible implementations for when we may need to expand our options.)

> (btw, instead of labels, nice, big tooltips could be useful although not very mobile friendly).

agreed, great point. IME, tab bars tend to work well:

![image](https://cloud.githubusercontent.com/assets/203725/18089678/15c30114-6efc-11e6-9876-79ae0c9e8c29.png)

![image](https://cloud.githubusercontent.com/assets/203725/18089694/296d3c2a-6efc-11e6-86e2-c672525ab827.png)

and, popover menus when necessary to hide actions that are more secondary:

![image](https://cloud.githubusercontent.com/assets/203725/18089685/233ae118-6efc-11e6-8fe9-98ef829cd49b.png)

also, re: tooltips (which are touched on already in #37 and #20), I'd recommend using https://frend.co/components/tooltip/

**Comment by ngokevin** [comment]
going to close for now. any icons we have now are infrequently used or not part of the target workflow (@feiss is the #1 user of the inspector!).

if we gain more functionality, we can reconsider adding menus and such. going to prioritize making the inspector useful / frictionless
