### ISSUE TITLE
Widget for `selector` / `selectorAll` property types

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-inspector#348]
Currently, a blank text field. Selector property types are pretty common. With Don's new physics constraints, they'd be used to add joints between entities.

Should have some widget magic to indicate it's a selector. Perhaps show list of matching entities as you type, or number of matching entities, or highlight the matching entities in the viewport (!).

**Comment by fernandojsg** [comment]
@ngokevin it actually just a html selector right? in the way that there're no constrains on it. 
Maybe a first version could consist on highlighting the matching entities on the scenegraph as we still don't support multiple highlight on the viewport.
The problem is that not all the selector will return an entity visible on the scenegraph, for example if using an asset selector.
Don't know if using something like the autocomplete list that will keep showing a list of matching that you can scroll but can't select could works...
