### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by MartijnEisses** [aframevr/aframe-inspector#568]
When I open the inspector in Chrome I get the error: 
`Failed to load resource: net::ERR_CONNECTION_REFUSED`
and then the next error every 5 seconds or so:
 `aframe-inspector.min.js:25 GET http://localhost:51234/ net::ERR_CONNECTION_REFUSED`

Is there something I can do about this?

**Comment by ngokevin** [comment]
It's polling for the aframe-watcher utility to see if it's available to highlight the icon. Useful to see if the watcher is active or not without having to click the Save button.

Possible to just ignore during Inspector sessions? When I use Inspector, I don't have console open much since I'm focused on visuals, not code.
