### ISSUE TITLE
Bad contrast between selection box color and list bullet

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-inspector#6]
![xxx](https://s3.amazonaws.com/f.cl.ly/items/0x08283L2T1X2c193m0C/Image%202016-06-30%20at%204.01.23%20PM.png?v=55c77c86)

**Comment by fernandojsg** [comment]
Regardless the colors, this is something inherited from three.js editor where they used the colors to show entity types, each color represent a light, camera, or whatever. 
We already have this functionality with the component's icons, so I don't know if it's a bit redundant to have colored bullets or just keep then using the same base color. Right now I've one color for `a-entity` elements and another one for `non-a-entity`, and maybe if we hover the icon it will show the html element name. Do you think it could be useful that way?
Regarding the colors, I'll ask Dennis to give some higher contrast color range.

**Comment by caseyyee** [comment]
Agree its redundant.   I was confused as to what those dots were even.

**Comment by caseyyee** [comment]
To be honest, I think those icons and bullets are confusing anyways.  I don't see much value in having them since one entity can have any number of components.  so it's not that really helpful.

![image](https://cloud.githubusercontent.com/assets/1560884/16597699/27436a74-42af-11e6-9883-28956b178484.png)

Unity scene hierarchy doesn't have any icons.   They rely heavily on the label.   Which is more descriptive than any icon.

**Comment by fernandojsg** [comment]
The bullets we could just remove and change them for arrows like treeview. But I believe the icons will give you a quick look of the kind of entity you're dealing with, for example if you're looking for the camera or light you'll get it quite fast. This is the approach 3d software like cinema4d or 3dsmax follow.

**Comment by caseyyee** [comment]
Sure, for camera yes, I agree that would be useful.

**Comment by fernandojsg** [comment]
Fixed on https://github.com/aframevr/aframe-editor/pull/105
