### ISSUE TITLE
cloning an entity with mixin value will sometimes not apply the mixin correctly to the cloned entity

### ISSUE THREAD

**Issue by kfarr** [aframevr/aframe-inspector#689]
This is the second of 2 errors encountered using the duplicate (clone) entity feature (keyboard shortcut `d`)

* when an entity is cloned, the value(s) for the `mixin` attribute are copied. See https://github.com/aframevr/aframe-inspector/issues/688 for a deeper explanation.
* sometimes, but not always, when cloning an entity the mixin will not apply correctly to the newly cloned entity. For example, if the mixin is a gltf model sometimes the newly cloned entity will not display the gltf model.
* sometimes, but not always, when choosing a new mixin value for an existing entity the new mixin value will not apply correctly. For example, if the existing mixin is a gltf model A and a user chooses gltf model B, sometimes the newly cloned entity will not display any gltf model and appear empty.

Workaround:
We encountered this issue in both cases in 3DStreet for some models. We came up with a workaround where we set the mixin value first to '' and then re-set the mixin value to the desired value. This appears to work in all cases that we have tested.

Here are the 2 cases where we use this workaround in 3DStreet:
* When updating a single mixin*: https://github.com/3DStreet/3dstreet-editor/blob/master/src/components/components/Mixins.js#L66
* When cloning an entity: https://github.com/3DStreet/3dstreet-editor/blob/master/src/lib/entity.js#L142

here is a video of a duplicated entity not showing the mixin value as expected. the UI workaround is to remove the mixin and re-apply the same mixin:
https://github.com/aframevr/aframe-inspector/assets/470477/b7cb3adb-1408-4709-9cd2-3a65b4990ca4

*note that a single mixin concept is unique to 3dstreet, default aframe-inspector uses select multiple

here is the URL to reproduce:
https://mixin-gltf-url-error.glitch.me/

here are instructions to reproduce:
press ctl-alt-i to invoke the inspector, select the mixin firetruck, while the truck entity is selected press `d`, note how the firetruck is not visible in the newly cloned entity.

expected behavior:
- when cloning an item the duplicated item displays the cloned entity's mixin as expected

**Comment by vincentfretin** [comment]
@3DStreet sponsored me to work on this issue. Thank you! https://github.com/c-frame/sponsorship/issues/3

**Comment by vincentfretin** [comment]
https://github.com/aframevr/aframe/issues/2823 is probably related to this issue.

**Comment by vincentfretin** [comment]
Removing the mixin is removing the gltf-model component but you don't see it disappears in the right panel (that's another issue, a forceUpdate is missing on the ComponentsContainer React component for the entityupdate event with component "mixin"), you can select another entity and select the previous entity back to see it. Another issue is the UI is not updating with the mixin name at the top of the right panel and in the left panel when you add or remove a mixin.
When you add the mixin back, it adds the gltf-model component again. That's why your workaround work.

I see in the DOM that when gltf-model is set with a mixin, that gltf-model (empty) is shown.
If I set a gltf-model component with an url on an entity without mixin, the DOM shows the gltf-model="theurl"
The main issue I think may be that gltf-model="" appears in the DOM.
I don't know at this point if this is something we can fix in aframe, related to mixin, to not show components in DOM so that native [`cloneNode(true)`](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) api works correctly, or if we'll need workaround like you did after cloning. I need to dig this further.
Also currently in the right panel we don't visualize that a component is coming from a mixin and that removing a mixin will remove associated components.

**Comment by vincentfretin** [comment]
You said that you reproduce the issue sometimes, but not always. I reproduce it every time. Maybe you don't reproduce it when the gltf-model component is really set on the entity, overriding the mixin, even if it's the same url, you can see it in with Chrome inspector, if you see the url, then the gltf-model component is set directly and duplicating the entity will show the model.

**Comment by vincentfretin** [comment]
Some other notes:
In the DOM it shows
`<a-entity position="0 0 -9" mixin="fire-truck-rig" gltf-model=""></a-entity>` 
or
`<a-entity position="0 0 -9" mixin="fire-truck-rig" gltf-model="thesameurlasmixin"></a-entity>` if you touched the url via the right panel

If you use "copy entity HTML to clipboard" button, you get
`<a-entity position="0 0 -9" mixin="fire-truck-rig"></a-entity>`

**Comment by vincentfretin** [comment]
@kfarr Looking at `getEntityClipboardRepresentation` function that is used for the "copy entity HTML to clipboard" feature, that is using `prepareForSerialization` and `optimizeComponents` functions 

https://github.com/aframevr/aframe-inspector/blob/72fd46159801ad37a14e87448611607b5d09a36e/src/lib/entity.js#L157-L219

it does all the logic of removing attributes if it's inherited from mixin (so the gltf-model component).
The function documentation is exactly this: "Removes from copy those components or components' properties that comes from
primitive attributes, mixins, injected default components or schema defaults."
It actually does a clone of each child one by one and getting the outerHTML of the clone.

I think for the duplicate feature we should really just change the line
`const clone = entity.cloneNode(true);`
by 
`const clone = prepareForSerialization(entity);`
This solves the issue completely.

**Comment by vincentfretin** [comment]
For your single mixin feature, you should just keep your workaround, that's fine. It indeed force it to remove the gltf-model component and create another one.

**Comment by vincentfretin** [comment]
PR #696 fixes the issue.
For UI parts that are not updated, I created another issue #697 and #698.

**Comment by kfarr** [comment]
confirming this works as expected for me, can close once @dmarcos merges #696
