### ISSUE TITLE
Selecting a-scene crashes the React UI on aframe 1.6.0 and master

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#741]
![image](https://github.com/user-attachments/assets/faccd18f-b0e5-4a6b-90e5-a3cabf42bc3b)

It works on aframe 1.5.0

**Comment by vincentfretin** [comment]
Context of the error:
`props = {name: 'camera', schema: {…}, data: null, componentname: 'screenshot', isSingle: false, …}`
`props.entity.getDOMAttribute(props.componentname)` is undefined

![image](https://github.com/user-attachments/assets/15f81425-9954-42c1-ab78-ff64a3497099)

on master:
```js
document.querySelector('a-scene').getDOMAttribute('screenshot')
undefined
document.querySelector('a-scene').getAttribute('screenshot')
{width: 4096, height: 2048, camera: null}
```

on aframe 1.5.0
```js
document.querySelector('a-scene').getDOMAttribute('screenshot')
{}
```

It's an easy fix, I can just rewrite the line to
```js
entity.getDOMAttribute(props.componentname)?.[props.name]
```

@mrxz Do you confirm the change of behavior of `getDOMAttribute` returning `undefined` instead of `{}` was expected for a component set with`sceneEl.setAttribute('screenshot', '')` https://github.com/aframevr/aframe/blob/c590f85b30e0577442e4bf73c3f5fdedf1f21eab/src/core/scene/a-scene.js#L83 here with the latest changes aframe changes?

**Comment by mrxz** [comment]
> @mrxz Do you confirm the change of behavior of `getDOMAttribute` returning `undefined` instead of `{}` was expected for a component set with`sceneEl.setAttribute('screenshot', '')` https://github.com/aframevr/aframe/blob/c590f85b30e0577442e4bf73c3f5fdedf1f21eab/src/core/scene/a-scene.js#L83 here with the latest changes aframe changes?

@vincentfretin 
Partially, one of the goals was to reduce memory usage, so the internal `attrValue` is only leased from the object pool when needed. As a result there are more situations where it will be `undefined` when accessed directly or through `getDOMAttribute`. In particular for object based single-property components and components with no/empty schemas.

I was, however, under the impression that the outward behaviour of `getDOMAttribute` hadn't changed for multi-property components. Mainly because [this 8 year old unit test](https://github.com/aframevr/aframe/blob/master/tests/core/a-entity.test.js#L731-L734) remained green, but I now see that the test has a bug as `shallowDeepEqual(undefined, {})` surprisingly passes.

**Comment by vincentfretin** [comment]
We should at least fix the test to change the tested result then?
