### ISSUE TITLE
Enable switching between translate/rotate/scale by clicking attribute's label

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/aframe-inspector#79]
Let the user switch between the different gizmos by clicking on the name of the attribute they want to change.

**Comment by caseyyee** [comment]
I think this is the same issue: https://github.com/aframevr/aframe-editor/issues/73

Also probably better to have a separate tool?  

ie: 
Unity
![image](https://cloud.githubusercontent.com/assets/1560884/16601451/6bd2bbec-42c1-11e6-8d9f-c5e1981bb0e3.png)

sketchup
![image](https://cloud.githubusercontent.com/assets/1560884/16601459/7415042c-42c1-11e6-89ad-47733a10dc58.png)

It's not obvious otherwise.

**Comment by arturitu** [comment]
I think the separate tool is a good option with translate/rotate/scale and visible (the common properties)
And with a double-click to change automatically between translate/rotate/scale.

![image](https://cloud.githubusercontent.com/assets/5744112/16677725/df42e05c-44d8-11e6-9c00-f4e35c0c54ce.png)
With the avobe sketch each object could have a different tool selected, perhaps is more common to have only one selected by default for all:
![image](https://cloud.githubusercontent.com/assets/5744112/16678268/c839b4e4-44dd-11e6-851b-bad6eceb6e7f.png)

**Comment by caseyyee** [comment]
I kind of like it in it's own tool bar.   It's easier to access that way without the noise of the properties panel.   that is what i am doing with the editor 90% of the time is picking and placing items.

**Comment by fernandojsg** [comment]
As discussed, closed by https://github.com/aframevr/aframe-editor/pull/173
